// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportManagementSystem.Data;

#nullable disable

namespace TransportManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512075154_AddMotorizationRequestsTable")]
    partial class AddMotorizationRequestsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransportManagementSystem.Models.Admin", b =>
                {
                    b.Property<int>("Admin_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Admin_Id"));

                    b.Property<string>("Admin_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Admin_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Admin_PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Admin_Id");

                    b.ToTable("Admin_tbl", "Security");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Alert", b =>
                {
                    b.Property<int>("Alert_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Alert_Id"));

                    b.Property<long>("Alert_BusId")
                        .HasColumnType("bigint");

                    b.Property<string>("Alert_DeliveryChannel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Alert_Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("Alert_PersonnelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Alert_SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Alert_Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Alert_TrajectoryId")
                        .HasColumnType("int");

                    b.Property<string>("Alert_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Alert_Id");

                    b.HasIndex("Alert_BusId");

                    b.HasIndex("Alert_PersonnelId");

                    b.HasIndex("Alert_TrajectoryId");

                    b.ToTable("Alert_tbl", "Service");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Bus", b =>
                {
                    b.Property<long>("Bus_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Bus_Id"));

                    b.Property<string>("Bus_Brand")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Bus_Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Bus_Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Bus_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Bus_CurrentDriverId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Bus_CurrentFragmentId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Bus_CurrentLatitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Bus_CurrentLongitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<DateTime?>("Bus_LastLocationUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bus_Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bus_PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Bus_Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Bus_UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Bus_Year")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentOccupancy")
                        .HasColumnType("int");

                    b.Property<int?>("Trajectory_Id")
                        .HasColumnType("int");

                    b.HasKey("Bus_Id");

                    b.HasIndex("Bus_CurrentDriverId");

                    b.HasIndex("Bus_CurrentFragmentId");

                    b.HasIndex("Trajectory_Id");

                    b.ToTable("Bus_tbl", "Transport");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.BusFragmentAssignment", b =>
                {
                    b.Property<int>("Assignment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Assignment_Id"));

                    b.Property<long>("Bus_Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("End_DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fragment_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start_DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("Assignment_Id");

                    b.HasIndex("Bus_Id");

                    b.HasIndex("Fragment_Id");

                    b.ToTable("BusFragmentAssignment_tbl", "Assignment");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.BusTrajectoryAssignment", b =>
                {
                    b.Property<int>("BTA_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BTA_Id"));

                    b.Property<long>("BTA_BusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("BTA_EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BTA_StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BTA_Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BTA_TrajectoryId")
                        .HasColumnType("int");

                    b.HasKey("BTA_Id");

                    b.ToTable("BusTrajectoryAssignment_tbl", "Assignment");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Driver", b =>
                {
                    b.Property<long>("Driver_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("Driver_AssignedBusId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Driver_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Driver_Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Driver_ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Driver_FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Driver_LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Driver_LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Driver_LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Driver_PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Driver_Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Driver_UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Driver_id");

                    b.HasIndex("Driver_AssignedBusId");

                    b.ToTable("Driver_tbl", "Security");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.DriverFragmentAssignment", b =>
                {
                    b.Property<int>("Assignment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Assignment_Id"));

                    b.Property<long>("Driver_Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("End_DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fragment_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start_DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("Assignment_Id");

                    b.HasIndex("Driver_Id");

                    b.HasIndex("Fragment_Id");

                    b.ToTable("DriverFragmentAssignment_tbl", "Assignment");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.DriverMission", b =>
                {
                    b.Property<int>("Mission_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mission_Id"));

                    b.Property<long>("Bus_Id")
                        .HasColumnType("bigint");

                    b.Property<long>("Driver_Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Mission_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalWorkers")
                        .HasColumnType("int");

                    b.Property<int>("WorkersDropped")
                        .HasColumnType("int");

                    b.HasKey("Mission_Id");

                    b.ToTable("DriverMissions_tbl", "Service");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.DriverPerformance", b =>
                {
                    b.Property<int>("Performance_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Performance_Id"));

                    b.Property<decimal?>("AverageDelayMinutes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Driver_Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastTripDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OnTimeTrips")
                        .HasColumnType("int");

                    b.Property<int>("TotalTrips")
                        .HasColumnType("int");

                    b.Property<int>("Trajectory_Id")
                        .HasColumnType("int");

                    b.HasKey("Performance_Id");

                    b.HasIndex("Driver_Id");

                    b.HasIndex("Trajectory_Id");

                    b.ToTable("DriverPerformance_tbl", "Service");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.FragmentStop", b =>
                {
                    b.Property<int>("Stop_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Stop_Id"));

                    b.Property<int>("Fragment_Id")
                        .HasColumnType("int");

                    b.Property<int>("Stop_Order")
                        .HasColumnType("int");

                    b.Property<int>("TS_Id")
                        .HasColumnType("int");

                    b.Property<int>("Workers_At_Stop")
                        .HasColumnType("int");

                    b.HasKey("Stop_Id");

                    b.HasIndex("Fragment_Id");

                    b.HasIndex("TS_Id");

                    b.ToTable("FragmentStop_tbl", "Transport");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Personnel", b =>
                {
                    b.Property<long>("Personnel_Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("AssignedBusId")
                        .HasColumnType("bigint");

                    b.Property<int?>("AssignedFragmentId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedStopId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedTrajectoryId")
                        .HasColumnType("int");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAssigned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMotorized")
                        .HasColumnType("bit");

                    b.Property<string>("Personnel_Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Personnel_City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Personnel_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Personnel_DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Personnel_Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Personnel_Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Personnel_EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Personnel_FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Personnel_Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Personnel_LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Personnel_Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Personnel_Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Personnel_PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Personnel_Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Personnel_UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Personnel_Id");

                    b.HasIndex("AssignedBusId");

                    b.HasIndex("AssignedFragmentId");

                    b.HasIndex("AssignedStopId");

                    b.HasIndex("AssignedTrajectoryId");

                    b.ToTable("Personnel_tbl", "Security");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.PersonnelTrajectoryAssignment", b =>
                {
                    b.Property<int>("PTA_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PTA_Id"));

                    b.Property<DateTime>("PTA_EffectiveFromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PTA_EffectiveToDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PTA_PersonnelId")
                        .HasColumnType("bigint");

                    b.Property<string>("PTA_Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PTA_StopId")
                        .HasColumnType("int");

                    b.Property<int>("PTA_TrajectoryId")
                        .HasColumnType("int");

                    b.HasKey("PTA_Id");

                    b.HasIndex("PTA_PersonnelId");

                    b.HasIndex("PTA_StopId");

                    b.HasIndex("PTA_TrajectoryId");

                    b.ToTable("PersonnelTrajectoryAssignments_tbl", "Assignment");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.SuggestedStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SuggestedStops_tbl", "Transport");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Trajectory", b =>
                {
                    b.Property<int>("Trajectory_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trajectory_Id"));

                    b.Property<string>("Trajectory_Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Trajectory_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Trajectory_Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Trajectory_DistanceKm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Trajectory_EndLatitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Trajectory_EndLongitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<int?>("Trajectory_EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Trajectory_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Trajectory_StartLatitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Trajectory_StartLongitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Trajectory_Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Trajectory_UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Trajectory_Id");

                    b.ToTable("Trajectory_tbl", "Transport");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.TrajectoryFragment", b =>
                {
                    b.Property<int>("Fragment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Fragment_Id"));

                    b.Property<DateTime?>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Fragment_Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fragment_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("Total_Workers")
                        .HasColumnType("int");

                    b.Property<int>("Trajectory_Id")
                        .HasColumnType("int");

                    b.HasKey("Fragment_Id");

                    b.HasIndex("Trajectory_Id");

                    b.ToTable("TrajectoryFragment_tbl", "Transport");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.TrajectorySchedule", b =>
                {
                    b.Property<int>("TSched_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TSched_Id"));

                    b.Property<string>("TSched_DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TSched_DepartureTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TSched_ReturnTime")
                        .HasColumnType("time");

                    b.Property<int>("TSched_TrajectoryId")
                        .HasColumnType("int");

                    b.HasKey("TSched_Id");

                    b.ToTable("TrajectoryShedule_tbl", "Transport");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.TrajectoryStop", b =>
                {
                    b.Property<int>("TS_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TS_Id"));

                    b.Property<decimal>("TS_Latitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("TS_Longitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("TS_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TS_OrderIndex")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TS_PlannedArrivalTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TS_PlannedDepartureTime")
                        .HasColumnType("time");

                    b.Property<int>("TS_TrajectoryId")
                        .HasColumnType("int");

                    b.HasKey("TS_Id");

                    b.HasIndex("TS_TrajectoryId");

                    b.ToTable("TrajectoryStop_tbl", "Transport");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Alert", b =>
                {
                    b.HasOne("TransportManagementSystem.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("Alert_BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportManagementSystem.Models.Personnel", "Personnel")
                        .WithMany()
                        .HasForeignKey("Alert_PersonnelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportManagementSystem.Models.Trajectory", "Trajectory")
                        .WithMany()
                        .HasForeignKey("Alert_TrajectoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Personnel");

                    b.Navigation("Trajectory");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Bus", b =>
                {
                    b.HasOne("TransportManagementSystem.Models.Driver", "CurrentDriver")
                        .WithMany()
                        .HasForeignKey("Bus_CurrentDriverId");

                    b.HasOne("TransportManagementSystem.Models.TrajectoryFragment", "AssignedFragment")
                        .WithMany()
                        .HasForeignKey("Bus_CurrentFragmentId");

                    b.HasOne("TransportManagementSystem.Models.Trajectory", null)
                        .WithMany("AssignedBuses")
                        .HasForeignKey("Trajectory_Id");

                    b.Navigation("AssignedFragment");

                    b.Navigation("CurrentDriver");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.BusFragmentAssignment", b =>
                {
                    b.HasOne("TransportManagementSystem.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("Bus_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportManagementSystem.Models.TrajectoryFragment", "Fragment")
                        .WithMany()
                        .HasForeignKey("Fragment_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Fragment");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Driver", b =>
                {
                    b.HasOne("TransportManagementSystem.Models.Bus", "AssignedBus")
                        .WithMany()
                        .HasForeignKey("Driver_AssignedBusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedBus");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.DriverFragmentAssignment", b =>
                {
                    b.HasOne("TransportManagementSystem.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("Driver_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportManagementSystem.Models.TrajectoryFragment", "Fragment")
                        .WithMany()
                        .HasForeignKey("Fragment_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Fragment");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.DriverPerformance", b =>
                {
                    b.HasOne("TransportManagementSystem.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("Driver_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportManagementSystem.Models.Trajectory", "Trajectory")
                        .WithMany()
                        .HasForeignKey("Trajectory_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Trajectory");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.FragmentStop", b =>
                {
                    b.HasOne("TransportManagementSystem.Models.TrajectoryFragment", "Fragment")
                        .WithMany("FragmentStops")
                        .HasForeignKey("Fragment_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransportManagementSystem.Models.TrajectoryStop", "TrajectoryStop")
                        .WithMany()
                        .HasForeignKey("TS_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fragment");

                    b.Navigation("TrajectoryStop");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Personnel", b =>
                {
                    b.HasOne("TransportManagementSystem.Models.Bus", "AssignedBus")
                        .WithMany("AssignedPersonnel")
                        .HasForeignKey("AssignedBusId");

                    b.HasOne("TransportManagementSystem.Models.TrajectoryFragment", "AssignedFragment")
                        .WithMany()
                        .HasForeignKey("AssignedFragmentId");

                    b.HasOne("TransportManagementSystem.Models.TrajectoryStop", "AssignedStop")
                        .WithMany()
                        .HasForeignKey("AssignedStopId");

                    b.HasOne("TransportManagementSystem.Models.Trajectory", "AssignedTrajectory")
                        .WithMany()
                        .HasForeignKey("AssignedTrajectoryId");

                    b.Navigation("AssignedBus");

                    b.Navigation("AssignedFragment");

                    b.Navigation("AssignedStop");

                    b.Navigation("AssignedTrajectory");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.PersonnelTrajectoryAssignment", b =>
                {
                    b.HasOne("TransportManagementSystem.Models.Personnel", "Personnel")
                        .WithMany()
                        .HasForeignKey("PTA_PersonnelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransportManagementSystem.Models.TrajectoryStop", "Stop")
                        .WithMany()
                        .HasForeignKey("PTA_StopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransportManagementSystem.Models.Trajectory", "Trajectory")
                        .WithMany()
                        .HasForeignKey("PTA_TrajectoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personnel");

                    b.Navigation("Stop");

                    b.Navigation("Trajectory");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.TrajectoryFragment", b =>
                {
                    b.HasOne("TransportManagementSystem.Models.Trajectory", "Trajectory")
                        .WithMany()
                        .HasForeignKey("Trajectory_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trajectory");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.TrajectoryStop", b =>
                {
                    b.HasOne("TransportManagementSystem.Models.Trajectory", "Trajectory")
                        .WithMany("Stops")
                        .HasForeignKey("TS_TrajectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trajectory");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Bus", b =>
                {
                    b.Navigation("AssignedPersonnel");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Trajectory", b =>
                {
                    b.Navigation("AssignedBuses");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.TrajectoryFragment", b =>
                {
                    b.Navigation("FragmentStops");
                });
#pragma warning restore 612, 618
        }
    }
}
