// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportManagementSystem.Data;

#nullable disable

namespace TransportManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransportManagementSystem.Models.Bus", b =>
                {
                    b.Property<int>("Bus_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bus_Id"));

                    b.Property<string>("Bus_Brand")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Bus_Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Bus_Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Bus_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Bus_CurrentDriverId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Bus_CurrentLatitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Bus_CurrentLongitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<int?>("Bus_CurrentTrajectoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Bus_LastLocationUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bus_Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bus_PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Bus_Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Bus_UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Bus_Year")
                        .HasColumnType("int");

                    b.HasKey("Bus_Id");

                    b.ToTable("Bus_tbl", "Transport");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Driver", b =>
                {
                    b.Property<int>("Driver_id")
                        .HasColumnType("int");

                    b.Property<int?>("Driver_AssignedBusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Driver_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Driver_Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Driver_EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("Driver_ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Driver_FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Driver_LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Driver_LicenseExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Driver_LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Driver_PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Driver_PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Driver_ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Driver_ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Driver_Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Driver_UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Driver_id");

                    b.ToTable("Driver_tbl", "Security");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Personnel", b =>
                {
                    b.Property<int>("Personnel_Id")
                        .HasColumnType("int");

                    b.Property<string>("Personnel_Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Personnel_City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Personnel_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Personnel_DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Personnel_Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Personnel_Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Personnel_EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Personnel_FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Personnel_Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Personnel_LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Personnel_Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Personnel_Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Personnel_PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Personnel_Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Personnel_UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Personnel_Id");

                    b.ToTable("Personnel_tbl", "Security");
                });

            modelBuilder.Entity("TransportManagementSystem.Models.Trajectory", b =>
                {
                    b.Property<int>("Trajectory_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trajectory_Id"));

                    b.Property<string>("Trajectory_Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Trajectory_CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Trajectory_Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Trajectory_DistanceKm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Trajectory_EndLatitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Trajectory_EndLongitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<int?>("Trajectory_EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Trajectory_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Trajectory_StartLatitude")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Trajectory_StartLongitude")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Trajectory_Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Trajectory_UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Trajectory_Id");

                    b.ToTable("Trajectory_tbl", "Transport");
                });
#pragma warning restore 612, 618
        }
    }
}
